services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: multiareaportal-sql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Portal@Pass2022"
      MSSQL_PID: "Developer"
    ports:
      - "1434:1433"
    volumes:
      - multiareaportal-sqldata:/var/opt/mssql
    restart: unless-stopped

volumes:
  multiareaportal-sqldata:
